version: "3.8"

services:
  backend:
    build:
      context: ./server
    container_name: avito-backend-container
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build:
      context: ./client
    container_name: avito-frontend-container
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
